runtime: python27
threadsafe: true
api_version: 1

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico))$
  static_files: dist/\1
  upload: dist/(.*)
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html